version: "3"

services:
  db_postgres_clients:
    image: postgres
    container_name: db_postgres_clients
    restart: always
    ports:
      - 5005:5432
    env_file:
      - .env
    volumes:
      - pg_clients:/var/lib/postgresql/data

  node_app_clients:
    container_name: node_app_clients
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_clients
    env_file:
      - .env

volumes:
  pg_clients: